### ISSUE TITLE
can not open the link for documentation

### ISSUE THREAD

**Issue by xieyuheng** [eschulte/asm#1]
---

I am curious about this repo :)
and also about the use of org-mode

README says that:
Usage
See documentation in epr-asm.org and online at http://epr.adaptive.cs.unm.edu/asm/about.html
but I can not open the link

---

**Comment by eschulte** [comment]
This is an old repository and that page has apparently not been maintained at unm.

See http://dijkstra.cs.virginia.edu/genprog/ for a site on the parent project.

For a more current maintained version of this code (in common lisp) see the following.
https://github.com/eschulte/software-evolution
http://eschulte.github.io/software-evolution/index.html#Top
